### ISSUE TITLE
Publication of XML grammar for Protection Profiles, Modules, and Functional Packages

### ISSUE THREAD

**Issue by amasino** [commoncriteria/commoncriteria.github.io#2]
The XML grammar to validate XML files does not seem to be publicly available. A description of the structure for documents, for instance using XSD or DTD files, would be much appreciated.

Also, there seem to be discrepancies between the grammar used in the different documents, and some ambiguous semantics for tags.

**Comment by kgal** [comment]
The grammar is defined in RelaxNG and available here: https://github.com/commoncriteria/transforms/tree/master/schemas. 

A more JavaDoc-style interface is available here:
 
* https://commoncriteria.github.io/pp/transforms/CCProtectionProfile.rng.html
* https://commoncriteria.github.io/pp/transforms/CCModule.rng.html
